/*
* generated by Xtext
*/
package org.xtext.example.maven.ui.contentassist;

import org.xtext.example.maven.ui.contentassist.AbstractMyDsl1ProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MyDsl1ProposalProvider extends AbstractMyDsl1ProposalProvider {

}
