/*
 * generated by Xtext
 */
package org.xtext.example.maven;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDsl1RuntimeModule extends org.xtext.example.maven.AbstractMyDsl1RuntimeModule {

}
