/*
* generated by Xtext
*/
package org.xtext.example.maven.ui.contentassist;

import org.xtext.example.maven.ui.contentassist.AbstractMyDsl2ProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MyDsl2ProposalProvider extends AbstractMyDsl2ProposalProvider {

}
