/*
 * generated by Xtext
 */
package org.xtext.example.maven.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyDsl1UiModule extends org.xtext.example.maven.ui.AbstractMyDsl1UiModule {
	public MyDsl1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
